/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define GPIODEN			(1U<<3)
#define PIN13			(1U<<13)
#define LED_PIN			PIN13



int main(void)
{

	RCC->AHB1ENR |=GPIODEN;

	GPIOD->MODER &= 0x00;
	GPIOD->MODER |= (1U<<26);

	while(1)
	{
		GPIOD->ODR ^=LED_PIN;
		for(int i=0;i<100000;i++);

	}
}
